package com.worms.db.iservices;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public interface IService<T>{
	
	static final Logger LOG = LogManager.getLogger();
	
	/**
	 * save an instance in the database
	 * @param instance : the instance saved
	 * @return The saved instance. it's mostly used to get back the autoGenerated id of the instance saved.
	 */
	public T add(T instance);
}
