package com.worms.db.entities;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InventaireId generated by hbm2java
 */
@Embeddable
public class ItemInInventaire_Id implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int idUser;
	private int idItem;

	public ItemInInventaire_Id() {
	}

	public ItemInInventaire_Id(int idUser, int idItem) {
		this.idUser = idUser;
		this.idItem = idItem;
	}

	@Column(name = "id_user", nullable = false)
	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	@Column(name = "id_item", nullable = false)
	public int getIdItem() {
		return this.idItem;
	}

	public void setIdItem(int idItem) {
		this.idItem = idItem;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ItemInInventaire_Id))
			return false;
		ItemInInventaire_Id castOther = (ItemInInventaire_Id) other;

		return (this.getIdUser() == castOther.getIdUser()) && (this.getIdItem() == castOther.getIdItem());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdUser();
		result = 37 * result + this.getIdItem();
		return result;
	}

}
