package com.worms.db.entities;
// Generated 2 avr. 2017 03:36:22 by Hibernate Tools 5.2.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Inventaire generated by hbm2java
 */
@Entity
@Table(name = "inventaire", catalog = "game")
public class ItemInInventaire implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private ItemInInventaire_Id id;
	private Item item;
	private User user;
	private int munitions;

	public ItemInInventaire() {
	}

	public ItemInInventaire(ItemInInventaire_Id id, Item item, User user, int munitions) {
		this.id = id;
		this.item = item;
		this.user = user;
		this.munitions = munitions;
	}

	@EmbeddedId
	@AttributeOverrides({ 
		@AttributeOverride(name = "idUser", column = @Column(name = "id_user", nullable = false)),
		@AttributeOverride(name = "idItem", column = @Column(name = "id_item", nullable = false)) 
	})
	public ItemInInventaire_Id getId() {
		return this.id;
	}

	public void setId(ItemInInventaire_Id id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_item", nullable = false, insertable = false, updatable = false)
	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_user", nullable = false, insertable = false, updatable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "munitions", nullable = false)
	public int getMunitions() {
		return this.munitions;
	}

	public void setMunitions(int munitions) {
		this.munitions = munitions;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Inventaire [id=");
		builder.append(id);
		builder.append(", item=");
		builder.append(item);
		builder.append(", user=");
		builder.append(user);
		builder.append(", munitions=");
		builder.append(munitions);
		builder.append("]");
		return builder.toString();
	}

}
