package com.worms.db.entities;
// Generated 2 avr. 2017 03:36:22 by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "game")
public class User implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private String login;
	private String password;
	private String email;
	private Integer points;
	private Set<ItemInInventaire> itemsInInventaire = new HashSet<ItemInInventaire>(0);

	public User() {
	}

	public User(String login, String password, String email, Integer points, Set<ItemInInventaire> itemsInInventaire) {
		this.login = login;
		this.password = password;
		this.email = email;
		this.points = points;
		this.itemsInInventaire = itemsInInventaire;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "login")
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "points")
	public Integer getPoints() {
		return this.points;
	}

	public void setPoints(Integer points) {
		this.points = points;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "user")
	public Set<ItemInInventaire> getItemsInInventaire() {
		return this.itemsInInventaire;
	}

	public void setItemsInInventaire(Set<ItemInInventaire> itemsInInventaire) {
		this.itemsInInventaire = itemsInInventaire;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("User [id=");
		builder.append(id);
		builder.append(", login=");
		builder.append(login);
		builder.append(", password=");
		builder.append(password);
		builder.append(", email=");
		builder.append(email);
		builder.append(", points=");
		builder.append(points);
		builder.append(", inventaires=");
		builder.append(itemsInInventaire);
		builder.append("]");
		return builder.toString();
	}

}
