package com.worms.db.entities;
// Generated 27 avr. 2017 17:03:09 by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Item generated by hbm2java
 */
@Entity
@Table(name = "item", catalog = "game")
public class Item implements java.io.Serializable {

	private Integer id;
	private String designation;
	private int stock;
	private Set<ItemInInventaire> inventaires = new HashSet<ItemInInventaire>(0);

	public Item() {
	}

	public Item(String designation, int stock) {
		this.designation = designation;
		this.stock = stock;
	}

	public Item(String designation, int stock, Set<ItemInInventaire> inventaires) {
		this.designation = designation;
		this.stock = stock;
		this.inventaires = inventaires;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "designation", nullable = false, length = 45)
	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	@Column(name = "stock", nullable = false)
	public int getStock() {
		return this.stock;
	}

	public void setStock(int stock) {
		this.stock = stock;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "item")
	public Set<ItemInInventaire> getInventaires() {
		return this.inventaires;
	}

	public void setInventaires(Set<ItemInInventaire> inventaires) {
		this.inventaires = inventaires;
	}

}
