package com.worms.db.entities;
// Generated 13 avr. 2017 14:41:15 by Hibernate Tools 5.2.1.Final

import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 * Item generated by hbm2java
 */
@Entity
@Component
@Table(name = "item", catalog = "game")
public class Item implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private String designation;
	private int stock;
	
	@Autowired
	private Set<ItemInInventaire> itemsInInventaire;

	public Item() {
	}

	public Item(String designation, int stock) {
		this.designation = designation;
		this.stock = stock;
	}

	public Item(String designation, int stock, Set<ItemInInventaire> itemsInInventaire) {
		this.designation = designation;
		this.stock = stock;
		this.itemsInInventaire = itemsInInventaire;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "designation", nullable = false, length = 45)
	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	@Column(name = "stock", nullable = false)
	public int getStock() {
		return this.stock;
	}

	public void setStock(int stock) {
		this.stock = stock;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "item")
	public Set<ItemInInventaire> getItemsInInventaire() {
		return this.itemsInInventaire;
	}

	public void setItemsInInventaire(Set<ItemInInventaire> itemsInInventaire) {
		this.itemsInInventaire = itemsInInventaire;
	}

}
