package com.worms.db.entities;
// Generated 27 avr. 2017 17:03:09 by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "game", uniqueConstraints = { @UniqueConstraint(columnNames = "email"), @UniqueConstraint(columnNames = "login") })
public class User implements java.io.Serializable {

	private Integer id;
	private String login;
	private String password;
	private String email;
	private Integer points;
	private String nickname;
	private Integer gold;
	private Integer gem;
	private Integer level;
	private Integer exp;
	private Set<ItemInInventaire> inventaires = new HashSet<ItemInInventaire>(0);

	public User() {
	}

	public User(String login, String password, String email, Integer points, String nickname, Integer gold, Integer gem, Integer level, Integer exp, Set<ItemInInventaire> inventaires) {
		this.login = login;
		this.password = password;
		this.email = email;
		this.points = points;
		this.nickname = nickname;
		this.gold = gold;
		this.gem = gem;
		this.level = level;
		this.exp = exp;
		this.inventaires = inventaires;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "login", unique = true)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "email", unique = true)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "points")
	public Integer getPoints() {
		return this.points;
	}

	public void setPoints(Integer points) {
		this.points = points;
	}

	@Column(name = "nickname", length = 45)
	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	@Column(name = "gold")
	public Integer getGold() {
		return this.gold;
	}

	public void setGold(Integer gold) {
		this.gold = gold;
	}

	@Column(name = "gem")
	public Integer getGem() {
		return this.gem;
	}

	public void setGem(Integer gem) {
		this.gem = gem;
	}

	@Column(name = "level")
	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	@Column(name = "exp")
	public Integer getExp() {
		return this.exp;
	}

	public void setExp(Integer exp) {
		this.exp = exp;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<ItemInInventaire> getInventaires() {
		return this.inventaires;
	}

	public void setInventaires(Set<ItemInInventaire> inventaires) {
		this.inventaires = inventaires;
	}

}
